language: objective-c
osx_image: xcode7.3
xcode_project: dooit.xcodeproj
xcode_scheme: dooit
xcode_sdk: iphonesimulator
script: set -o pipefail && xcodebuild test -project $TRAVIS_XCODE_PROJECT -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK | xcpretty
notifications:
  email: false
